Public Class LicenciasBE

    Public Property IdLicencia As Integer
    Public Property NumeroSolicitud As String
    Public Property IdLicenciaTipo As Integer
    Public Property LicenciaTipo As String
    Public Property IdLocal As Integer
    Public Property RazonSocial As String
    Public Property RazonComercial As String
    Public Property Fecha As Date
    Public Property IdSolicitante As Integer
    Public Property FechaIngreso As Date
    Public Property FechaPeriodoInicio As Date
    Public Property FechaPeriodoFin As Date
    Public Property Descripcion As String
    Public Property OtrosAnexos As String
    Public Property UsuarioRegistro As Integer
    Public Property EstadoRevisado As Boolean
    Public Property Telefon As String
    Public Property EstadoAnulado As Boolean
    Public Property IdCargoSolicitante As Integer
    Public Property CandidadDias As Integer
    Public Property FechaIncorporacion As Date
    Public Property FechaEvaluacionRRHH As Date
    Public Property UsuarioEvaluacionRRHH As Integer
    Public Property NombreEmpleado As String
    Public Property IdCargo As Integer
    Public Property Cargo As String
    Public Property Dni As String
    Public Property IdGrupoEnfermedad As Integer
    Public Property IdSubGrupoEnfermedad As Integer
    Public Property GrupoEnfermedad As String
    Public Property SubGrupoEnfermedad As String
    Public Property IdProcedencia As Integer
    Public Property IdMotivoEnfermedad As Integer
    Public Property NumeroDescansoMedico As String
    Public Property IdMesEvaluacion As Integer
    Public Property EstadoPago As Boolean
    Public Property Declaracion As Boolean

    Public Property DiasSubSidio As Integer
    Public Property DiasRecuperados As Integer
    Public Property DiasAnulados As Integer
    Public Property NitEssalud As String
    Public Property FechaRecepcion As Date
    Public Property IdTipoObservacionEnfermedad As Integer
    Public Property DetalleDescansoMedico As String
    Public Property IdBanco As Integer
    Public Property NumeroCheque As String
    Public Property MontoSubSidiado As Double
    Public Property EstadoAprobadoDescansoMedico As Boolean
    Public Property IdMotivoDerechoLey As Integer
    Public Property ObservacionLicenciaOtros As String
End Class
