'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class XRDesignRibbonControllerResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MC.SistemaGestionRRHH.XRDesignRibbonControllerResources", GetType(XRDesignRibbonControllerResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignBottom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignBottom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignHorizontalCenters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignHorizontalCenters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignLeft() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignLeft", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignRight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignRight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignToGrid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignToGrid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignTop() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignTop", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignVerticalCenters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignVerticalCenters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_BackColor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_BackColor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_BringToFront() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_BringToFront", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CenterHorizontally() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CenterHorizontally", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CenterVertically() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CenterVertically", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CopyLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CopyLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Cut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Cut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Exit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Exit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ExitLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ExitLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Font() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Font", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontBold() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontBold", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontItalic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontItalic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontUnderline() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontUnderline", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ForeColor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ForeColor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceConcatenate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceConcatenate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceDecrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceDecrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceIncrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceIncrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceMakeEqual() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceMakeEqual", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlBackward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlBackwardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackwardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlFind() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlFind", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlFindLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlFindLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlForward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlForward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlForwardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlForwardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlHome() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlHome", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlHomeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlHomeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlRefresh() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefresh", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlRefreshLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefreshLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlStop() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlStop", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlStopLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlStopLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyCenter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyCenter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyJustify() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyJustify", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyLeft() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyLeft", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyRight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyRight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReport() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReport", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportWizard() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizard", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportWizardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_OpenFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_OpenFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_OpenFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_OpenFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Paste() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Paste", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_PasteLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_PasteLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Redo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Redo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_RedoLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_RedoLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Report() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Report", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveAll() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveAll", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveAllLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveAllLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileAs() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAs", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileAsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Scripts() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Scripts", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ScriptsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ScriptsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SendToBack() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SendToBack", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControl() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControl", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControlHeight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlHeight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControlWidth() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlWidth", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToGrid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToGrid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Undo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Undo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_UndoLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_UndoLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceConcatenate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceConcatenate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceDecrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceDecrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceIncrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceIncrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceMakeEqual() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceMakeEqual", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Windows() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Windows", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_WindowsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_WindowsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Zoom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Zoom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomIn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomInLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomInLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomOut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomOutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomOutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
